In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv("datasetler/orders.csv")

In [3]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [9]:
df["year"].value_counts()

year
2014    17531
2013    13799
2012    10962
2011     8998
Name: count, dtype: int64

In [10]:
df.drop(["order_id","customer_name","product_id","product_name"],axis=1,inplace=True)

In [12]:
df["order_date"].unique()

array(['1/1/2011', '2/1/2011', '3/1/2011', ..., '29/12/2014',
       '30/12/2014', '31/12/2014'], shape=(1430,), dtype=object)

In [13]:
df.head()

,order_date,ship_date,ship_mode,segment,state,country,market,region,category,sub_category,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,1/1/2011,6/1/2011,Standard Class,Consumer,Constantine,Algeria,Africa,Africa,Office Supplies,Storage,408,2,0.0,106.140,35.46,Medium,2011
1,1/1/2011,8/1/2011,Standard Class,Consumer,New South Wales,Australia,APAC,Oceania,Office Supplies,Supplies,120,3,0.1,36.036,9.72,Medium,2011
2,1/1/2011,5/1/2011,Second Class,Consumer,Budapest,Hungary,EMEA,EMEA,Office Supplies,Storage,66,4,0.0,29.640,8.17,High,2011
3,1/1/2011,5/1/2011,Second Class,Home Office,Stockholm,Sweden,EU,North,Office Supplies,Paper,45,3,0.5,-26.055,4.82,High,2011
4,1/1/2011,8/1/2011,Standard Class,Consumer,New South Wales,Australia,APAC,Oceania,Furniture,Furnishings,114,5,0.1,37.770,4.70,Medium,2011

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
df['ship_date'] = pd.to_datetime(df['ship_date'], dayfirst=True)
#object olan tarihleri tarih formatına getirdim.

In [15]:
df["time"]=df["ship_date"]-df["order_date"]

In [18]:
df.drop(["order_date","ship_date"],axis=1,inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ship_mode       51290 non-null  object
 1   segment         51290 non-null  object
 2   state           51290 non-null  object
 3   country         51290 non-null  object
 4   market          51290 non-null  object
 5   region          51290 non-null  object
 6   category        51290 non-null  object
 7   sub_category    51290 non-null  object
 8   sales           51290 non-null  object
 9   quantity        51290 non-null  int64
 10  discount        51290 non-null  float64
 11  profit          51290 non-null  float64
 12  shipping_cost   51290 non-null  float64
 13  order_priority  51290 non-null  object
 14  year            51290 non-null  int64
 15  time            51290 non-null  timedelta64[ns]
dtypes: float64(3), int64(2), object(10), timedelta64[ns](1)
memory usage: 6.3+ MB

In [20]:
df.time.value_counts()

time
4 days    14434
5 days    11221
2 days     7026
6 days     6255
3 days     5035
7 days     3057
0 days     2600
1 days     1662
Name: count, dtype: int64

In [21]:
df["time"] = df["time"].dt.days

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ship_mode       51290 non-null  object
 1   segment         51290 non-null  object
 2   state           51290 non-null  object
 3   country         51290 non-null  object
 4   market          51290 non-null  object
 5   region          51290 non-null  object
 6   category        51290 non-null  object
 7   sub_category    51290 non-null  object
 8   sales           51290 non-null  object
 9   quantity        51290 non-null  int64
 10  discount        51290 non-null  float64
 11  profit          51290 non-null  float64
 12  shipping_cost   51290 non-null  float64
 13  order_priority  51290 non-null  object
 14  year            51290 non-null  int64
 15  time            51290 non-null  int64
dtypes: float64(3), int64(3), object(10)
memory usage: 6.3+ MB

In [23]:
df.ship_mode.value_counts()

ship_mode
Standard Class    30775
Second Class      10309
First Class        7505
Same Day           2701
Name: count, dtype: int64

In [24]:
ship_mapping = {
    'Standard Class': 0,
    'Second Class': 1,
    'First Class': 2,
    'Same Day': 3
}

In [25]:
df["ship_mode"]=df["ship_mode"].map(ship_mapping)

In [27]:
df.segment.value_counts()

segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

In [28]:
df = pd.get_dummies(df, columns=['segment'], prefix='seg')

In [29]:
df.head()

,ship_mode,state,country,market,region,category,sub_category,sales,quantity,discount,profit,shipping_cost,order_priority,year,time,seg_Consumer,seg_Corporate,seg_Home Office
0,0,Constantine,Algeria,Africa,Africa,Office Supplies,Storage,408,2,0.0,106.140,35.46,Medium,2011,5,True,False,False
1,0,New South Wales,Australia,APAC,Oceania,Office Supplies,Supplies,120,3,0.1,36.036,9.72,Medium,2011,7,True,False,False
2,1,Budapest,Hungary,EMEA,EMEA,Office Supplies,Storage,66,4,0.0,29.640,8.17,High,2011,4,True,False,False
3,1,Stockholm,Sweden,EU,North,Office Supplies,Paper,45,3,0.5,-26.055,4.82,High,2011,4,False,False,True
4,0,New South Wales,Australia,APAC,Oceania,Furniture,Furnishings,114,5,0.1,37.770,4.70,Medium,2011,7,True,False,False

In [30]:
df.order_priority.value_counts()

order_priority
Medium      29433
High        15501
Critical     3932
Low          2424
Name: count, dtype: int64

In [31]:
onem={
    "Low":0,
    "Medium":1,
    "High":2,
    "Critical":3
}

In [32]:
df["order_priority"]=df["order_priority"].map(onem)

In [33]:
df.head()

,ship_mode,state,country,market,region,category,sub_category,sales,quantity,discount,profit,shipping_cost,order_priority,year,time,seg_Consumer,seg_Corporate,seg_Home Office
0,0,Constantine,Algeria,Africa,Africa,Office Supplies,Storage,408,2,0.0,106.140,35.46,1,2011,5,True,False,False
1,0,New South Wales,Australia,APAC,Oceania,Office Supplies,Supplies,120,3,0.1,36.036,9.72,1,2011,7,True,False,False
2,1,Budapest,Hungary,EMEA,EMEA,Office Supplies,Storage,66,4,0.0,29.640,8.17,2,2011,4,True,False,False
3,1,Stockholm,Sweden,EU,North,Office Supplies,Paper,45,3,0.5,-26.055,4.82,2,2011,4,False,False,True
4,0,New South Wales,Australia,APAC,Oceania,Furniture,Furnishings,114,5,0.1,37.770,4.70,1,2011,7,True,False,False

In [34]:
df.market.value_counts()

market
APAC      11002
LATAM     10294
EU        10000
US         9994
EMEA       5029
Africa     4587
Canada      384
Name: count, dtype: int64

In [35]:
df.region.value_counts()

region
Central           11117
South              6645
EMEA               5029
North              4785
Africa             4587
Oceania            3487
West               3203
Southeast Asia     3129
East               2848
North Asia         2338
Central Asia       2048
Caribbean          1690
Canada              384
Name: count, dtype: int64

In [36]:
df.sub_category.value_counts()

sub_category
Binders        6152
Storage        5059
Art            4883
Paper          3538
Chairs         3434
Phones         3357
Furnishings    3170
Accessories    3075
Labels         2606
Envelopes      2435
Supplies       2425
Fasteners      2420
Bookcases      2411
Copiers        2223
Appliances     1755
Machines       1486
Tables          861
Name: count, dtype: int64

In [37]:
df.country.value_counts()

country
United States    9994
Australia        2837
France           2827
Mexico           2644
Germany          2065
                 ...
South Sudan         2
Swaziland           2
Chad                2
Eritrea             2
Bahrain             2
Name: count, Length: 147, dtype: int64

In [42]:
#market ve region bölgeleri için one hot yapıcam
df = pd.get_dummies(df, columns=['market', 'region'], prefix=['mkt', 'reg'])

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 36 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ship_mode           51290 non-null  int64
 1   state               51290 non-null  object
 2   country             51290 non-null  object
 3   category            51290 non-null  object
 4   sub_category        51290 non-null  object
 5   sales               51290 non-null  object
 6   quantity            51290 non-null  int64
 7   discount            51290 non-null  float64
 8   profit              51290 non-null  float64
 9   shipping_cost       51290 non-null  float64
 10  order_priority      51290 non-null  int64
 11  year                51290 non-null  int64
 12  time                51290 non-null  int64
 13  seg_Consumer        51290 non-null  bool
 14  seg_Corporate       51290 non-null  bool
 15  seg_Home Office     51290 non-null  bool
 16  mkt_APAC            51290 non-null  bool
 17  mkt_Africa          51290 non-null  bool
 18  mkt_Canada          51290 non-null  bool
 19  mkt_EMEA            51290 non-null  bool
 20  mkt_EU              51290 non-null  bool
 21  mkt_LATAM           51290 non-null  bool
 22  mkt_US              51290 non-null  bool
 23  reg_Africa          51290 non-null  bool
 24  reg_Canada          51290 non-null  bool
 25  reg_Caribbean       51290 non-null  bool
 26  reg_Central         51290 non-null  bool
 27  reg_Central Asia    51290 non-null  bool
 28  reg_EMEA            51290 non-null  bool
 29  reg_East            51290 non-null  bool
 30  reg_North           51290 non-null  bool
 31  reg_North Asia      51290 non-null  bool
 32  reg_Oceania         51290 non-null  bool
 33  reg_South           51290 non-null  bool
 34  reg_Southeast Asia  51290 non-null  bool
 35  reg_West            51290 non-null  bool
dtypes: bool(23), float64(3), int64(5), object(5)
memory usage: 6.2+ MB

In [44]:
#countryleri de ülkenin ortalama değerine bölerek hesaplama yapıcam. yani türkiyenin ortalama değeri neyse artık
#türkiye yerine mesela 49 yazacak

country_means = df.groupby('country')['profit'].mean()
df['country'] = df['country'].map(country_means)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 36 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ship_mode           51290 non-null  int64
 1   state               51290 non-null  object
 2   country             51290 non-null  float64
 3   category            51290 non-null  object
 4   sub_category        51290 non-null  object
 5   sales               51290 non-null  object
 6   quantity            51290 non-null  int64
 7   discount            51290 non-null  float64
 8   profit              51290 non-null  float64
 9   shipping_cost       51290 non-null  float64
 10  order_priority      51290 non-null  int64
 11  year                51290 non-null  int64
 12  time                51290 non-null  int64
 13  seg_Consumer        51290 non-null  bool
 14  seg_Corporate       51290 non-null  bool
 15  seg_Home Office     51290 non-null  bool
 16  mkt_APAC            51290 non-null  bool
 17  mkt_Africa          51290 non-null  bool
 18  mkt_Canada          51290 non-null  bool
 19  mkt_EMEA            51290 non-null  bool
 20  mkt_EU              51290 non-null  bool
 21  mkt_LATAM           51290 non-null  bool
 22  mkt_US              51290 non-null  bool
 23  reg_Africa          51290 non-null  bool
 24  reg_Canada          51290 non-null  bool
 25  reg_Caribbean       51290 non-null  bool
 26  reg_Central         51290 non-null  bool
 27  reg_Central Asia    51290 non-null  bool
 28  reg_EMEA            51290 non-null  bool
 29  reg_East            51290 non-null  bool
 30  reg_North           51290 non-null  bool
 31  reg_North Asia      51290 non-null  bool
 32  reg_Oceania         51290 non-null  bool
 33  reg_South           51290 non-null  bool
 34  reg_Southeast Asia  51290 non-null  bool
 35  reg_West            51290 non-null  bool
dtypes: bool(23), float64(4), int64(5), object(4)
memory usage: 6.2+ MB

In [47]:
pd.set_option('display.max_columns', None)
df.head()

,ship_mode,state,country,category,sub_category,sales,quantity,discount,profit,shipping_cost,order_priority,year,time,seg_Consumer,seg_Corporate,seg_Home Office,mkt_APAC,mkt_Africa,mkt_Canada,mkt_EMEA,mkt_EU,mkt_LATAM,mkt_US,reg_Africa,reg_Canada,reg_Caribbean,reg_Central,reg_Central Asia,reg_EMEA,reg_East,reg_North,reg_North Asia,reg_Oceania,reg_South,reg_Southeast Asia,reg_West
0,0,Constantine,46.461735,Office Supplies,Storage,408,2,0.0,106.140,35.46,1,2011,5,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
1,0,New South Wales,37.181869,Office Supplies,Supplies,120,3,0.1,36.036,9.72,1,2011,7,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,1,Budapest,48.514091,Office Supplies,Storage,66,4,0.0,29.640,8.17,2,2011,4,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
3,1,Stockholm,-86.302300,Office Supplies,Paper,45,3,0.5,-26.055,4.82,2,2011,4,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,0,New South Wales,37.181869,Furniture,Furnishings,114,5,0.1,37.770,4.70,1,2011,7,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [48]:
df.state.value_counts()

state
California       2001
England          1499
New York         1128
Texas             985
Ile-de-France     981
                 ...
Los Rios            1
Lima                1
Medea               1
Tanga               1
Inhambane           1
Name: count, Length: 1094, dtype: int64

In [49]:
df.drop("state",axis=1,inplace=True)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ship_mode           51290 non-null  int64
 1   country             51290 non-null  float64
 2   category            51290 non-null  object
 3   sub_category        51290 non-null  object
 4   sales               51290 non-null  object
 5   quantity            51290 non-null  int64
 6   discount            51290 non-null  float64
 7   profit              51290 non-null  float64
 8   shipping_cost       51290 non-null  float64
 9   order_priority      51290 non-null  int64
 10  year                51290 non-null  int64
 11  time                51290 non-null  int64
 12  seg_Consumer        51290 non-null  bool
 13  seg_Corporate       51290 non-null  bool
 14  seg_Home Office     51290 non-null  bool
 15  mkt_APAC            51290 non-null  bool
 16  mkt_Africa          51290 non-null  bool
 17  mkt_Canada          51290 non-null  bool
 18  mkt_EMEA            51290 non-null  bool
 19  mkt_EU              51290 non-null  bool
 20  mkt_LATAM           51290 non-null  bool
 21  mkt_US              51290 non-null  bool
 22  reg_Africa          51290 non-null  bool
 23  reg_Canada          51290 non-null  bool
 24  reg_Caribbean       51290 non-null  bool
 25  reg_Central         51290 non-null  bool
 26  reg_Central Asia    51290 non-null  bool
 27  reg_EMEA            51290 non-null  bool
 28  reg_East            51290 non-null  bool
 29  reg_North           51290 non-null  bool
 30  reg_North Asia      51290 non-null  bool
 31  reg_Oceania         51290 non-null  bool
 32  reg_South           51290 non-null  bool
 33  reg_Southeast Asia  51290 non-null  bool
 34  reg_West            51290 non-null  bool
dtypes: bool(23), float64(4), int64(5), object(3)
memory usage: 5.8+ MB

In [51]:
df.category.value_counts()

category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [52]:
df = pd.get_dummies(df, columns=["category"], prefix=["ctgry"])

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 37 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ship_mode              51290 non-null  int64
 1   country                51290 non-null  float64
 2   sub_category           51290 non-null  object
 3   sales                  51290 non-null  object
 4   quantity               51290 non-null  int64
 5   discount               51290 non-null  float64
 6   profit                 51290 non-null  float64
 7   shipping_cost          51290 non-null  float64
 8   order_priority         51290 non-null  int64
 9   year                   51290 non-null  int64
 10  time                   51290 non-null  int64
 11  seg_Consumer           51290 non-null  bool
 12  seg_Corporate          51290 non-null  bool
 13  seg_Home Office        51290 non-null  bool
 14  mkt_APAC               51290 non-null  bool
 15  mkt_Africa             51290 non-null  bool
 16  mkt_Canada             51290 non-null  bool
 17  mkt_EMEA               51290 non-null  bool
 18  mkt_EU                 51290 non-null  bool
 19  mkt_LATAM              51290 non-null  bool
 20  mkt_US                 51290 non-null  bool
 21  reg_Africa             51290 non-null  bool
 22  reg_Canada             51290 non-null  bool
 23  reg_Caribbean          51290 non-null  bool
 24  reg_Central            51290 non-null  bool
 25  reg_Central Asia       51290 non-null  bool
 26  reg_EMEA               51290 non-null  bool
 27  reg_East               51290 non-null  bool
 28  reg_North              51290 non-null  bool
 29  reg_North Asia         51290 non-null  bool
 30  reg_Oceania            51290 non-null  bool
 31  reg_South              51290 non-null  bool
 32  reg_Southeast Asia     51290 non-null  bool
 33  reg_West               51290 non-null  bool
 34  ctgry_Furniture        51290 non-null  bool
 35  ctgry_Office Supplies  51290 non-null  bool
 36  ctgry_Technology       51290 non-null  bool
dtypes: bool(26), float64(4), int64(5), object(2)
memory usage: 5.6+ MB

In [54]:
df.sub_category.value_counts()

sub_category
Binders        6152
Storage        5059
Art            4883
Paper          3538
Chairs         3434
Phones         3357
Furnishings    3170
Accessories    3075
Labels         2606
Envelopes      2435
Supplies       2425
Fasteners      2420
Bookcases      2411
Copiers        2223
Appliances     1755
Machines       1486
Tables          861
Name: count, dtype: int64

In [55]:
df.drop("sub_category",axis=1,inplace=True)

In [56]:
df.sales.value_counts()

sales
13       589
11       550
14       527
19       523
17       520
        ...
2,044      1
1,070      1
4,864      1
1,670      1
3,445      1
Name: count, Length: 2246, dtype: int64

In [57]:
df.head()

,ship_mode,country,sales,quantity,discount,profit,shipping_cost,order_priority,year,time,seg_Consumer,seg_Corporate,seg_Home Office,mkt_APAC,mkt_Africa,mkt_Canada,mkt_EMEA,mkt_EU,mkt_LATAM,mkt_US,reg_Africa,reg_Canada,reg_Caribbean,reg_Central,reg_Central Asia,reg_EMEA,reg_East,reg_North,reg_North Asia,reg_Oceania,reg_South,reg_Southeast Asia,reg_West,ctgry_Furniture,ctgry_Office Supplies,ctgry_Technology
0,0,46.461735,408,2,0.0,106.140,35.46,1,2011,5,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,0,37.181869,120,3,0.1,36.036,9.72,1,2011,7,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False
2,1,48.514091,66,4,0.0,29.640,8.17,2,2011,4,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
3,1,-86.302300,45,3,0.5,-26.055,4.82,2,2011,4,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False
4,0,37.181869,114,5,0.1,37.770,4.70,1,2011,7,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ship_mode              51290 non-null  int64
 1   country                51290 non-null  float64
 2   sales                  51290 non-null  object
 3   quantity               51290 non-null  int64
 4   discount               51290 non-null  float64
 5   profit                 51290 non-null  float64
 6   shipping_cost          51290 non-null  float64
 7   order_priority         51290 non-null  int64
 8   year                   51290 non-null  int64
 9   time                   51290 non-null  int64
 10  seg_Consumer           51290 non-null  bool
 11  seg_Corporate          51290 non-null  bool
 12  seg_Home Office        51290 non-null  bool
 13  mkt_APAC               51290 non-null  bool
 14  mkt_Africa             51290 non-null  bool
 15  mkt_Canada             51290 non-null  bool
 16  mkt_EMEA               51290 non-null  bool
 17  mkt_EU                 51290 non-null  bool
 18  mkt_LATAM              51290 non-null  bool
 19  mkt_US                 51290 non-null  bool
 20  reg_Africa             51290 non-null  bool
 21  reg_Canada             51290 non-null  bool
 22  reg_Caribbean          51290 non-null  bool
 23  reg_Central            51290 non-null  bool
 24  reg_Central Asia       51290 non-null  bool
 25  reg_EMEA               51290 non-null  bool
 26  reg_East               51290 non-null  bool
 27  reg_North              51290 non-null  bool
 28  reg_North Asia         51290 non-null  bool
 29  reg_Oceania            51290 non-null  bool
 30  reg_South              51290 non-null  bool
 31  reg_Southeast Asia     51290 non-null  bool
 32  reg_West               51290 non-null  bool
 33  ctgry_Furniture        51290 non-null  bool
 34  ctgry_Office Supplies  51290 non-null  bool
 35  ctgry_Technology       51290 non-null  bool
dtypes: bool(26), float64(4), int64(5), object(1)
memory usage: 5.2+ MB

In [60]:
df.sales

0        408
1        120
2         66
3         45
4        114
        ...
51285     14
51286      4
51287     26
51288      7
51289      3
Name: sales, Length: 51290, dtype: object

In [61]:
#sales da bulunan verileri int türüne çeviriyorum
df['sales'] = pd.to_numeric(df['sales'], errors='coerce').fillna(0).astype(int)

In [63]:
df.year.value_counts()

year
2014    17531
2013    13799
2012    10962
2011     8998
Name: count, dtype: int64

In [64]:
df.drop("year",inplace=True,axis=1)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ship_mode              51290 non-null  int64
 1   country                51290 non-null  float64
 2   sales                  51290 non-null  int64
 3   quantity               51290 non-null  int64
 4   discount               51290 non-null  float64
 5   profit                 51290 non-null  float64
 6   shipping_cost          51290 non-null  float64
 7   order_priority         51290 non-null  int64
 8   time                   51290 non-null  int64
 9   seg_Consumer           51290 non-null  bool
 10  seg_Corporate          51290 non-null  bool
 11  seg_Home Office        51290 non-null  bool
 12  mkt_APAC               51290 non-null  bool
 13  mkt_Africa             51290 non-null  bool
 14  mkt_Canada             51290 non-null  bool
 15  mkt_EMEA               51290 non-null  bool
 16  mkt_EU                 51290 non-null  bool
 17  mkt_LATAM              51290 non-null  bool
 18  mkt_US                 51290 non-null  bool
 19  reg_Africa             51290 non-null  bool
 20  reg_Canada             51290 non-null  bool
 21  reg_Caribbean          51290 non-null  bool
 22  reg_Central            51290 non-null  bool
 23  reg_Central Asia       51290 non-null  bool
 24  reg_EMEA               51290 non-null  bool
 25  reg_East               51290 non-null  bool
 26  reg_North              51290 non-null  bool
 27  reg_North Asia         51290 non-null  bool
 28  reg_Oceania            51290 non-null  bool
 29  reg_South              51290 non-null  bool
 30  reg_Southeast Asia     51290 non-null  bool
 31  reg_West               51290 non-null  bool
 32  ctgry_Furniture        51290 non-null  bool
 33  ctgry_Office Supplies  51290 non-null  bool
 34  ctgry_Technology       51290 non-null  bool
dtypes: bool(26), float64(4), int64(5)
memory usage: 4.8 MB

In [66]:
# en kısa yol (Tüm tabloyu kontrol eder)ve boolları 1 ya da 0 ra çevirir:
df = df.replace({True: 1, False: 0})

C:\Users\HASAN\AppData\Local\Temp\ipykernel_25260\3506558701.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({True: 1, False: 0})

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ship_mode              51290 non-null  int64
 1   country                51290 non-null  float64
 2   sales                  51290 non-null  int64
 3   quantity               51290 non-null  int64
 4   discount               51290 non-null  float64
 5   profit                 51290 non-null  float64
 6   shipping_cost          51290 non-null  float64
 7   order_priority         51290 non-null  int64
 8   time                   51290 non-null  int64
 9   seg_Consumer           51290 non-null  int64
 10  seg_Corporate          51290 non-null  int64
 11  seg_Home Office        51290 non-null  int64
 12  mkt_APAC               51290 non-null  int64
 13  mkt_Africa             51290 non-null  int64
 14  mkt_Canada             51290 non-null  int64
 15  mkt_EMEA               51290 non-null  int64
 16  mkt_EU                 51290 non-null  int64
 17  mkt_LATAM              51290 non-null  int64
 18  mkt_US                 51290 non-null  int64
 19  reg_Africa             51290 non-null  int64
 20  reg_Canada             51290 non-null  int64
 21  reg_Caribbean          51290 non-null  int64
 22  reg_Central            51290 non-null  int64
 23  reg_Central Asia       51290 non-null  int64
 24  reg_EMEA               51290 non-null  int64
 25  reg_East               51290 non-null  int64
 26  reg_North              51290 non-null  int64
 27  reg_North Asia         51290 non-null  int64
 28  reg_Oceania            51290 non-null  int64
 29  reg_South              51290 non-null  int64
 30  reg_Southeast Asia     51290 non-null  int64
 31  reg_West               51290 non-null  int64
 32  ctgry_Furniture        51290 non-null  int64
 33  ctgry_Office Supplies  51290 non-null  int64
 34  ctgry_Technology       51290 non-null  int64
dtypes: float64(4), int64(31)
memory usage: 13.7 MB